package com.ssm.dao;

import com.ssm.entity.Caiwu;
import org.apache.ibatis.annotations.Param;

public interface CaiwuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caiwu
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caiwu
     *
     * @mbggenerated
     */
    int insert(Caiwu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caiwu
     *
     * @mbggenerated
     */
    int insertSelective(Caiwu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caiwu
     *
     * @mbggenerated
     */
    Caiwu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caiwu
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Caiwu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caiwu
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Caiwu record);
    Caiwu login(@Param("name") String name, @Param("pwd") String pwd);
}