package com.ssm.dao;

import com.ssm.entity.TblTeachercourse;

public interface TblTeachercourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_teachercourse
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_teachercourse
     *
     * @mbggenerated
     */
    int insert(TblTeachercourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_teachercourse
     *
     * @mbggenerated
     */
    int insertSelective(TblTeachercourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_teachercourse
     *
     * @mbggenerated
     */
    TblTeachercourse selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_teachercourse
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TblTeachercourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_teachercourse
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TblTeachercourse record);
}