package com.ssm.entity;

import com.ssm.service.impl.SlbServiceImpl;

import java.util.Iterator;
import java.util.List;

public class Employee {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.password
     *
     * @mbggenerated
     */
    private String password="0000";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.gwsalary
     *
     * @mbggenerated
     */
    public Float gwsalary=0f;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.xjsalary
     *
     * @mbggenerated
     */
    public Float xjsalary=0f;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.zwsalary
     *
     * @mbggenerated
     */
    public Float zwsalary=0f;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.jxsalary
     *
     * @mbggenerated
     */
    public Float jxsalary=0f;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.yfsalary
     *
     * @mbggenerated
     */
    public Float yfsalary=0f;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.grsds
     *
     * @mbggenerated
     */
    public Float grsds=0f;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.sfsalary
     *
     * @mbggenerated
     */
    public Float sfsalary=0f;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.dept
     *
     * @mbggenerated
     */
    private String dept;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.sex
     *
     * @mbggenerated
     */
    private String sex;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.birth
     *
     * @mbggenerated
     */
    private String birth;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.phone
     *
     * @mbggenerated
     */
    private String phone;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.username
     *
     * @mbggenerated
     */
    private String username;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.id
     *
     * @return the value of employee.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.id
     *
     * @param id the value for employee.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.name
     *
     * @return the value of employee.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.name
     *
     * @param name the value for employee.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.password
     *
     * @return the value of employee.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.password
     *
     * @param password the value for employee.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.gwsalary
     *
     * @return the value of employee.gwsalary
     *
     * @mbggenerated
     */
    public Float getGwsalary() {
        return gwsalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.gwsalary
     *
     * @param gwsalary the value for employee.gwsalary
     *
     * @mbggenerated
     */
    public void setGwsalary(Float gwsalary) {
        this.gwsalary = gwsalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.xjsalary
     *
     * @return the value of employee.xjsalary
     *
     * @mbggenerated
     */
    public Float getXjsalary() {
        return xjsalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.xjsalary
     *
     * @param xjsalary the value for employee.xjsalary
     *
     * @mbggenerated
     */
    public void setXjsalary(Float xjsalary) {
        this.xjsalary = xjsalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.zwsalary
     *
     * @return the value of employee.zwsalary
     *
     * @mbggenerated
     */
    public Float getZwsalary() {
        return zwsalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.zwsalary
     *
     * @param zwsalary the value for employee.zwsalary
     *
     * @mbggenerated
     */
    public void setZwsalary(Float zwsalary) {
        this.zwsalary = zwsalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.jxsalary
     *
     * @return the value of employee.jxsalary
     *
     * @mbggenerated
     */
    public Float getJxsalary() {
        return jxsalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.jxsalary
     *
     * @param jxsalary the value for employee.jxsalary
     *
     * @mbggenerated
     */
    public void setJxsalary(Float jxsalary) {
        this.jxsalary = jxsalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.yfsalary
     *
     * @return the value of employee.yfsalary
     *
     * @mbggenerated
     */
    public Float getYfsalary() {
        return yfsalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.yfsalary
     *
     * @param yfsalary the value for employee.yfsalary
     *
     * @mbggenerated
     */
    public void setYfsalary(Float yfsalary) {
        this.yfsalary = yfsalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.grsds
     *
     * @return the value of employee.grsds
     *
     * @mbggenerated
     */

    public Float getGrsds() {
        return grsds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.grsds
     *
     * @param grsds the value for employee.grsds
     *
     * @mbggenerated
     */
    public void setGrsds(float grsds) {
        this.grsds=grsds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.sfsalary
     *
     * @return the value of employee.sfsalary
     *
     * @mbggenerated
     */
    public Float getSfsalary() {
        sfsalary=yfsalary-grsds;
        return sfsalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.sfsalary
     *
     * @param sfsalary the value for employee.sfsalary
     *
     * @mbggenerated
     */
    public void setSfsalary(Float sfsalary) {
        this.sfsalary = sfsalary;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.date
     *
     * @mbggenerated
     */
    private String date;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.name
     *
     * @return the value of employee.name
     *
     * @mbggenerated
     */

    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.date
     *
     * @param date the value for employee.date
     *
     * @mbggenerated
     */
    public void setDate(String date) {
        this.date = date;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.birth
     *
     * @return the value of employee.birth
     *
     * @mbggenerated
     */
    public String getBirth() {
        return birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.birth
     *
     * @param birth the value for employee.birth
     *
     * @mbggenerated
     */
    public void setBirth(String birth) {
        this.birth = birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.dept
     *
     * @return the value of employee.dept
     *
     * @mbggenerated
     */
    public String getDept() {
        return dept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.dept
     *
     * @param dept the value for employee.dept
     *
     * @mbggenerated
     */
    public void setDept(String dept) {
        this.dept = dept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.phone
     *
     * @return the value of employee.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.phone
     *
     * @param phone the value for employee.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.sex
     *
     * @return the value of employee.sex
     *
     * @mbggenerated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.sex
     *
     * @param sex the value for employee.sex
     *
     * @mbggenerated
     */
    public void setSex(String sex) {
        this.sex = sex;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.username
     *
     * @return the value of employee.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.username
     *
     * @param username the value for employee.username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username;
    }
}
