package com.ssm.entity;

public class Slb {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slb.id
     *
     * @mbggenerated
     */
    private int id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slb.left1
     *
     * @mbggenerated
     */
    private Float left1;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slb.right1
     *
     * @mbggenerated
     */
    private Float right1;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slb.sl
     *
     * @mbggenerated
     */
    private Float sl;

    public int getId() {
        return id;
    }

    public Float getLeft1() {
        return left1;
    }

    public Float getRight1() {
        return right1;
    }

    public Float getSl() {
        return sl;
    }

    public void setId(int id) {
        this.id = id;
    }

    public void setLeft1(Float left) {
        this.left1 = left;
    }

    public void setRight1(Float right) {
        this.right1 = right;
    }

    public void setSl(Float sl) {
        this.sl = sl;
    }
}
