package com.ssm.entity;

public class TblTeachercourse {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_teachercourse.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_teachercourse.teacherId
     *
     * @mbggenerated
     */
    private Integer teacherid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_teachercourse.courseId
     *
     * @mbggenerated
     */
    private Integer courseid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_teachercourse.id
     *
     * @return the value of tbl_teachercourse.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_teachercourse.id
     *
     * @param id the value for tbl_teachercourse.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_teachercourse.teacherId
     *
     * @return the value of tbl_teachercourse.teacherId
     *
     * @mbggenerated
     */
    public Integer getTeacherid() {
        return teacherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_teachercourse.teacherId
     *
     * @param teacherid the value for tbl_teachercourse.teacherId
     *
     * @mbggenerated
     */
    public void setTeacherid(Integer teacherid) {
        this.teacherid = teacherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_teachercourse.courseId
     *
     * @return the value of tbl_teachercourse.courseId
     *
     * @mbggenerated
     */
    public Integer getCourseid() {
        return courseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_teachercourse.courseId
     *
     * @param courseid the value for tbl_teachercourse.courseId
     *
     * @mbggenerated
     */
    public void setCourseid(Integer courseid) {
        this.courseid = courseid;
    }
}